//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSACEncryption.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public uint keySize {
            get {
                return ((uint)(this["keySize"]));
            }
            set {
                this["keySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool multithreadedRSA {
            get {
                return ((bool)(this["multithreadedRSA"]));
            }
            set {
                this["multithreadedRSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint threadsRSA {
            get {
                return ((uint)(this["threadsRSA"]));
            }
            set {
                this["threadsRSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("encrypted.enc")]
        public string encryptedFile {
            get {
                return ((string)(this["encryptedFile"]));
            }
            set {
                this["encryptedFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("decrypted.dec")]
        public string decryptedFile {
            get {
                return ((string)(this["decryptedFile"]));
            }
            set {
                this["decryptedFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool inMemoryDecrypt {
            get {
                return ((bool)(this["inMemoryDecrypt"]));
            }
            set {
                this["inMemoryDecrypt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("privateKey.txt")]
        public string privateKeyExportFileName {
            get {
                return ((string)(this["privateKeyExportFileName"]));
            }
            set {
                this["privateKeyExportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("publicKey.txt")]
        public string publicKeyExportFileName {
            get {
                return ((string)(this["publicKeyExportFileName"]));
            }
            set {
                this["publicKeyExportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RSAKeys.txt")]
        public string encryptionKeysExportFileName {
            get {
                return ((string)(this["encryptionKeysExportFileName"]));
            }
            set {
                this["encryptionKeysExportFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int impExpKeySetting {
            get {
                return ((int)(this["impExpKeySetting"]));
            }
            set {
                this["impExpKeySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int showKeyInBase {
            get {
                return ((int)(this["showKeyInBase"]));
            }
            set {
                this["showKeyInBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":")]
        public char splitCharInExpImpFiles {
            get {
                return ((char)(this["splitCharInExpImpFiles"]));
            }
            set {
                this["splitCharInExpImpFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte encDecBlock {
            get {
                return ((byte)(this["encDecBlock"]));
            }
            set {
                this["encDecBlock"] = value;
            }
        }
    }
}
